version: "3.9"
services:
  #######
  # Business Partner Verifier
  #######
  bpa-verifier-api:
    image: mujtabaidrees94/business-partner-agent:api-0.9.0
    depends_on:
      - bpa-agent-verifier
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent-verifier:${ACAPY_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA_PORT}
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA_HOST}
        -Dbpa.scheme=${BPA_SCHEME}
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1044
      BPA_WEB_MODE: ${BPA_WEB_MODE}
      BPA_LEDGER_BROWSER: ${BPA_LEDGER_BROWSER}
      BPA_BOOTSTRAP_UN: ${BPA_BOOTSTRAP_UN}
      BPA_BOOTSTRAP_PW: ${BPA_BOOTSTRAP_PW}
      ACAPY_ENDPOINT: ${ACAPY_ENDPOINT}
      AGENT_NAME: ${AGENT_NAME}
      BPA_IMPRINT_URL: ${BPA_IMPRINT_URL}
      BPA_PRIVACY_POLICY_URL: ${BPA_PRIVACY_POLICY_URL}
      BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: ${BPA_CREDDEF_REVOCATION_REGISTRY_SIZE}
      BPA_WEBHOOK_KEY: ${BPA_WEBHOOK_KEY}
    ports:
      - ${BPA_PORT}:${BPA_PORT}
      - ${BPA_DEBUG_PORT}:${BPA_DEBUG_PORT}
    restart: always
  bpa-agent-verifier:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    depends_on:
      - bpa-wallet-db-verifier
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 15;
        aca-py start \
        --auto-provision \
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_HTTP_PORT} \
        --webhook-url '${BPA_WEBHOOK_URL}#${BPA_WEBHOOK_KEY}' \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --seed '${ACAPY_SEED}' \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --label '${AGENT_NAME}' \
        --debug-presentations \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \       
        ${ACAPY_TAILS_UPLOAD_URL} \   
        "
    ]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
  bpa-wallet-db-verifier:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL1_PORT}:5432
    volumes:
      - bpa-wallet-db-verifier:/var/lib/postgresql/data

#######
# Volumes
#######
volumes:
  bpa-wallet-db-verifier:
